FROM python:3.12-slim

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagster-webserver and dagster-daemon, and to load the DagsterInstance
RUN pip install --upgrade pip && \
    pip install pyarrow pymilvus

RUN pip install --upgrade pip && \
    pip install pyarrow pymilvus \
	&& pip install \
    dagster \
    dagster-postgres \
    dagster-docker \
    pandas \
    transformers \
    torch


WORKDIR /opt/dagster/app

COPY repo.py milvus_utils.py /opt/dagster/app/

COPY ./data/ /opt/dagster/app/

EXPOSE 4000

# CMD allows this to be overridden from run launchers or executors that want
# to run other commands against your repository
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "repo.py"]
