milvus:
  host: "milvus-standalone"
  port: "19530"
collections:
  question_answer:
    dimension: 128
    index_file_size: 1024
    metric_type: "L2"

  frequent_qustions:
    dimension: 128
    index_file_size: 1024
    metric_type: "L2"  

